### ISSUE TITLE
add_action and add_filter not get hints

### ISSUE THREAD

**Issue by anzawi** [junichi11/netbeans-wordpress-plugin#45]
Hi , 
thanks for this plugin , but when write 
add_action('[CTRL+Space]', '');
its not get hints !

**Comment by junichi11** [comment]
Could you write your exact steps and your directory structure to reproduce it?

**Comment by anzawi** [comment]
i am using netbeans v8.0.2.
i did what written in README.md.
everything work correctly except this

**Comment by junichi11** [comment]
- Are there warnings related to this plugin in IDE log?
- What's your OS?

**Comment by anzawi** [comment]
Worning : WARNING [org.openide.filesystems.Ordering]: Not all children in Templates/ marked with the position attribute: [WordPress], but some are: [Licenses, Privileged, Project, Recent, Services, Scripting, ClientSide, UnitTests, Html5Tests, XML, Other, Properties, SaaSServices]
-----------------------------------
my OS windows 8.0
-----------------------------

**Comment by junichi11** [comment]
That warning is not the cause. I tried to use Windows7. But it works fine in my environment. Could you provide logs since I'll provide a nbm for logging later?

![nb-wp-issue45](https://cloud.githubusercontent.com/assets/738383/7995919/ca496238-0b55-11e5-95ab-7a3faafef8ac.png)

#### my environment
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Java: 1.7.0_40; Java HotSpot(TM) 64-Bit Server VM 24.0-b56
Runtime: Java(TM) SE Runtime Environment 1.7.0_40-b43
System: Windows 7 version 6.1 running on amd64; MS932;

#### plugin version number
0.7.3

**Comment by anzawi** [comment]
Thank you, the problem has been resolved.
I will reinstall netbeans :).

thank you

**Comment by junichi11** [comment]
> Thank you, the problem has been resolved.

:+1:
